### ISSUE TITLE
BluePyOpte error during TM-fitting

### ISSUE THREAD

**Issue by NataliBarros** [BlueBrain/BluePyOpt#457]
I would like to replicate the multiple frequency TM-fitting for my data as it is done in here:
https://github.com/BlueBrain/BluePyOpt/blob/master/examples/tsodyksmarkramstp/tsodyksmarkramstp_multiplefreqs.ipynb

However when I run the code in my venv I get the following error when running the second cell with code:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [3], in <cell line: 13>()
     11 # Create BluePyOpt optimization and run 
     12 evaluator = tmevaluator.TsodyksMarkramEvaluator(data, optconf)
---> 13 opt = bpop.optimisations.DEAPOptimisation(evaluator, offspring_size=500, map_function=pool.map,
     14                                           eta=20, mutpb=0.3, cxpb=0.7)
     15 pop, hof, log, history = opt.run(max_ngen=50)
     17 # Get best individual

File ~/venv_jupyterhub/lib/python3.8/site-packages/bluepyopt/deapext/optimisations.py:146, in DEAPOptimisation.__init__(self, evaluator, use_scoop, seed, offspring_size, eta, mutpb, cxpb, map_function, hof, selector_name)
    143 # Create a DEAP toolbox
    144 self.toolbox = deap.base.Toolbox()
--> 146 self.setup_deap()

File ~/venv_jupyterhub/lib/python3.8/site-packages/bluepyopt/deapext/optimisations.py:204, in DEAPOptimisation.setup_deap(self)
    194 self.toolbox.register(
    195     "population",
    196     deap.tools.initRepeat,
    197     list,
    198     self.toolbox.Individual)
    200 # Register the evaluation function for the individuals
    201 # import deap_efel_eval1
    202 self.toolbox.register(
    203     "evaluate",
--> 204     self.evaluator.init_simulator_and_evaluate_with_lists
    205 )
    207 # Register the mate operator
    208 self.toolbox.register(
    209     "mate",
    210     deap.tools.cxSimulatedBinaryBounded,
    211     eta=ETA,
    212     low=LOWER,
    213     up=UPPER)

AttributeError: 'TsodyksMarkramEvaluator' object has no attribute 'init_simulator_and_evaluate_with_lists'
```
Can anybody help me with this issue? Thanks.

**Comment by wvangeit** [comment]
@anilbey , @AurelienJaquier , @DrTaDa , do you know if some recent change could have triggered this?

**Comment by AurelienJaquier** [comment]
We added this new method to the `Cellevaluator`, `init_simulator_and_evaluate_with_lists`, lately (the LFPy merge, or the Arbor merge, I don't remember exactly).
Since the evaluator in this example does not have a simulator to evaluate, implementing a `init_simulator_and_evaluate_with_lists` simply calling `evaluate_with_lists` should do the trick.
I'll open a PR.

**Comment by AurelienJaquier** [comment]
Fixed with PR #458

**Comment by NataliBarros** [comment]
Is this issue suppose to be fixed? I'm still having the same error when trying to run the code in my venv and after 
pip install --upgrade bluepyopt

**Comment by AurelienJaquier** [comment]
Strange, it is working on my side. 

You are running the notebook, right? Is the BluePyOpt version from which you run the noteboook also updated? There is a `tmevaluator.py` file in the same folder as the notebook. Does this file have the method `init_simulator_and_evaluate_with_lists` (line 86)?

**Comment by AurelienJaquier** [comment]
Then this is the reason it is not working on your side. This file (and also `tmevaluator_multiplefreqs.py`) have the `init_simulator_and_evaluate_with_lists` in up-to-date bluepyopt: https://github.com/BlueBrain/BluePyOpt/blob/master/examples/tsodyksmarkramstp/tmevaluator.py#L86

You should re-download the example folder from the github repo because the files in it have been updated.

**Comment by AurelienJaquier** [comment]
Great! Then I'll close this issue. :)
